export const allClasses = {
  'alpha-xi': 'Alpha Xi',
  'alpha-nu': 'Alpha Nu',
  'alpha-mu': 'Alpha Mu',
  'alpha-kappa': 'Alpha Kappa',
  'alpha-iota': 'Alpha Iota',
  'alpha-theta': 'Alpha Theta',
  'alpha-eta': 'Alpha Eta',
  'alpha-zeta': 'Alpha Zeta',
  'alpha-epsilon': 'Alpha Epsilon',
  'alpha-delta': 'Alpha Delta',
  'alpha-gamma': 'Alpha Gamma',
  'alpha-beta': 'Alpha Beta',
  'alpha-alpha': 'Alpha Alpha',
  psi: 'Psi',
  chi: 'Chi',
  phi: 'Phi',
  upsilon: 'Upsilon',
  tau: 'Tau',
  sigma: 'Sigma',
  rho: 'Rho',
  pi: 'Pi',
  omicron: 'Omicron',
  xi: 'Xi',
  nu: 'Nu',
  mu: 'Mu',
  kappa: 'Kappa',
  iota: 'Iota',
  theta: 'Theta',
  eta: 'Eta',
  zeta: 'Zeta',
  epsilon: 'Epsilon',
  delta: 'Delta',
  gamma: 'Gamma',
  beta: 'Beta',
  alpha: 'Alpha',
  charter: 'Charter',
  annex: 'Annex',
};
